include: package:pedantic/analysis_options.1.11.1.yaml


analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    #- use_key_in_widget_constructors