name: places
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  flutter_bloc: ^7.2.0
  flutter_mobx: ^2.0.6+1
  flutter_redux: ^0.10.0
  flutter_svg: ^0.22.0

  intl: ^0.17.0
  path_provider: any
  provider: ^6.0.0
  redux: ^5.0.0
  sqflite: any
  surf_lint_rules: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.6.0
  #flutter pub run dart_code_metrics:metrics analyze lib
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  mobx: ^2.0.7
  mobx_codegen: ^2.0.7

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/icon/
    - res/icon/points/
    - res/img/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Black.ttf
        - asset: res/fonts/Roboto-BlackItalic.ttf
        - asset: res/fonts/Roboto-Bold.ttf
        - asset: res/fonts/Roboto-BoldItalic.ttf
        - asset: res/fonts/Roboto-Italic.ttf
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-LightItalic.ttf
        - asset: res/fonts/Roboto-Medium.ttf
        - asset: res/fonts/Roboto-MediumItalic.ttf
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Thin.ttf
        - asset: res/fonts/Roboto-ThinItalic.ttf
